import {
  a11yDark,
  atomDark,
  base16AteliersulphurpoolLight,
  cb,
  coldarkCold,
  coldarkDark,
  coyWithoutShadows,
  coy,
  darcula,
  dark,
  dracula,
  duotoneDark,
  duotoneEarth,
  duotoneForest,
  duotoneLight,
  duotoneSea,
  duotoneSpace,
  funky,
  ghcolors,
  gruvboxDark,
  gruvboxLight,
  holiTheme,
  hopscotch,
  lucario,
  materialDark,
  materialLight,
  materialOceanic,
  nightOwl,
  nord,
  okaidia,
  oneDark,
  oneLight,
  pojoaque,
  prism,
  shadesOfPurple,
  solarizedDarkAtom,
  solarizedlight,
  synthwave84,
  tomorrow,
  twilight,
  vs,
  vscDarkPlus,
  xonokai,
  zTouch,
} from "react-syntax-highlighter/dist/esm/styles/prism";

import { HighlighterStyleType } from "@types";

export const highlighterStyles: HighlighterStyleType[] = [
  { name: "a11yDark", style: a11yDark },
  { name: "atomDark", style: atomDark },
  {
    name: "base16AteliersulphurpoolLight",
    style: base16AteliersulphurpoolLight,
  },
  { name: "cb", style: cb },
  { name: "coldarkCold", style: coldarkCold },
  { name: "coldarkDark", style: coldarkDark },
  { name: "coyWithoutShadows", style: coyWithoutShadows },
  { name: "coy", style: coy },
  { name: "darcula", style: darcula },
  { name: "dark", style: dark },
  { name: "dracula", style: dracula },
  { name: "duotoneDark", style: duotoneDark },
  { name: "duotoneEarth", style: duotoneEarth },
  { name: "duotoneForest", style: duotoneForest },
  { name: "duotoneLight", style: duotoneLight },
  { name: "duotoneSea", style: duotoneSea },
  { name: "duotoneSpace", style: duotoneSpace },
  { name: "funky", style: funky },
  { name: "ghcolors", style: ghcolors },
  { name: "gruvboxDark", style: gruvboxDark },
  { name: "gruvboxLight", style: gruvboxLight },
  { name: "holiTheme", style: holiTheme },
  { name: "hopscotch", style: hopscotch },
  { name: "lucario", style: lucario },
  { name: "materialDark", style: materialDark },
  { name: "materialLight", style: materialLight },
  { name: "materialOceanic", style: materialOceanic },
  { name: "nightOwl", style: nightOwl },
  { name: "nord", style: nord },
  { name: "okaidia", style: okaidia },
  { name: "oneDark", style: oneDark },
  { name: "oneLight", style: oneLight },
  { name: "pojoaque", style: pojoaque },
  { name: "prism", style: prism },
  { name: "shadesOfPurple", style: shadesOfPurple },
  { name: "solarizedDarkAtom", style: solarizedDarkAtom },
  { name: "solarizedlight", style: solarizedlight },
  { name: "synthwave84", style: synthwave84 },
  { name: "tomorrow", style: tomorrow },
  { name: "twilight", style: twilight },
  { name: "vs", style: vs },
  { name: "vscDarkPlus", style: vscDarkPlus },
  { name: "xonokai", style: xonokai },
  { name: "zTouch", style: zTouch },
];
